In [1]:
import pandas as pd
import numpy as np
from glob import glob
import re
import json
import os, torch
import pandas as pd
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID" 
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
# import stemmer as hindi_stemmer
%config Completer.use_jedi = False

In [156]:
from transformers import AutoTokenizer, AutoModel, AutoModelForSequenceClassification
# name = "xlm-roberta-base" #"bert-base-multilingual-uncased"
load_model = AutoModelForSequenceClassification.from_pretrained("/media/nas_mount/Zaki/hasoc/xlm-r/")
load_model.cuda()
tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base") ##, additional_special_tokens=["[SENSEP]"])

In [40]:
from transformers import AutoTokenizer, AutoModel, AutoModelForSequenceClassification
name = "bert-base-multilingual-uncased"
load_model = AutoModelForSequenceClassification.from_pretrained("/media/nas_mount/Zaki/hasoc/mbert/")
load_model.cuda()
tokenizer = AutoTokenizer.from_pretrained(name) #, additional_special_tokens=["[SENSEP]"])

In [155]:
del load_model

In [16]:
from transformers import AutoTokenizer, AutoModel, AutoModelForSequenceClassification
name = "ai4bharat/indic-bert"
load_model = AutoModelForSequenceClassification.from_pretrained("/media/nas_mount/Zaki/hasoc/model-validation/indic/")
load_model.cuda()
tokenizer = AutoTokenizer.from_pretrained(name) #, additional_special_tokens=["[SENSEP]"])

In [139]:
test_csv = pd.read_csv("processed_test.csv")
test_tweets = test_csv["text"].tolist()
tweet_ids = test_csv["tweet_id"].tolist()
len(test_tweets)
# test_csv

import json
import pandas as pd
with open('test_labels.json', 'r') as f:
    data = json.load(f)
test_labels_json = pd.DataFrame({"id" : list(data.keys()), "label" : list(data.values())}, index=None)
# test_labels = test_labels["label"].to_list()
# test_labels

In [141]:
test_labels_json #["id"].tolist()

id label
0     1397136107108663298   HOF
1     1397138267867287552  NONE
2     1397144674524024832  NONE
3     1397174263522619399   HOF
4     1397138594079264768  NONE
...                   ...   ...
1343  1392431810303324164  NONE
1344  1392429419013181442  NONE
1345  1392429719795036164  NONE
1346  1392432270032572426   HOF
1347  1392436468308578306  NONE

[1348 rows x 2 columns]

In [153]:
# test_labels_json.reset_index(inplace=True)
test_labels = []
for i in range(len(test_csv)):
    id1 = int(tweet_ids[i])
#     print(id1)
    label = test_labels_json.loc[test_labels_json["id"]==str(id1)]["label"].tolist()
#     print(label)
    test_labels.append(label[0])

In [154]:
test_labels

['NONE',
 'NONE',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'NONE',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'NONE',
 'N

['HOF',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'NONE',
 'HOF',
 'NONE',
 '

### model testing for train-val split

In [4]:
def get_binary_labels(labels):
    for i, label in enumerate(labels):
        if(label=="HOF"):
            labels[i] = 1
        else:
            labels[i] = 0

    return np.array(labels) 

data = pd.read_csv("processed_data_punc.csv")
tweets = data["tweet"].tolist()
labels = data["label"].tolist()
import sklearn
from sklearn.model_selection import StratifiedShuffleSplit

sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=0)
sss.get_n_splits(tweets, labels)
tweets = np.array(tweets)
labels = get_binary_labels(labels)

for train_index, test_index in sss.split(tweets, labels):
    print("TRAIN:", train_index, "TEST:", test_index)
    x_train, x_test = tweets[train_index], tweets[test_index]
    y_train, y_test = labels[train_index], labels[test_index]

TRAIN: [4464 1219 4378 ... 4281 4454  482] TEST: [5223 4077 3257 ... 3994 1494 3310]


In [99]:
load_model.eval()

XLMRobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(250002, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0): RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (La

In [157]:
from tqdm import tqdm
def encode_data(test_sentences):
    test_input_ids = []
    test_attention_masks = []

    # For every sentence...
    for i, sent in enumerate(tqdm(test_sentences)):
        encoded_dict = tokenizer.encode_plus(
                            sent,                      # Sentence to encode.
                            add_special_tokens = True, # Add '[CLS]' and '[SEP]'
                            max_length = 512,           # Pad & truncate all sentences.
                            pad_to_max_length = True,
                            return_attention_mask = True,   # Construct attn. masks.
                            return_tensors = 'pt',     # Return pytorch tensors.
                            truncation=True
                       )

        test_input_ids.append(encoded_dict['input_ids'])
        test_attention_masks.append(encoded_dict['attention_mask'])
        
    return test_input_ids, test_attention_masks


def get_predictions(trained_model, test_input_ids, test_attention_masks):
    predictions = []
    for i in tqdm(range(len(test_input_ids))):
        b_input_ids = torch.cat([test_input_ids[i]], dim=0).cuda()
        b_attention_masks = torch.cat([test_attention_masks[i]], dim=0).cuda()

        with torch.no_grad():
            (logits) = trained_model(b_input_ids, 
                              token_type_ids=None, 
                              attention_mask=b_attention_masks,
                              labels=None)
        b_input_ids = b_input_ids.detach()
        b_attention_masks = b_attention_masks.detach()
        logits = torch.nn.functional.softmax(logits[0]).cpu()
        predictions+=logits
    return predictions

test_input_ids, test_attention_masks = encode_data(test_tweets)
# test_input_ids, test_attention_masks = encode_data(x_test)

  0%|          | 0/1348 [00:00<?, ?it/s]/home/zaki/.conda/envs/thesis/lib/python3.7/site-packages/transformers/tokenization_utils_base.py:2190: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,
100%|██████████| 1348/1348 [00:00<00:00, 2695.84it/s]


In [158]:
predictions = get_predictions(load_model, test_input_ids, test_attention_masks)
print(predictions)

100%|██████████| 1348/1348 [00:28<00:00, 46.91it/s]


[tensor([0.9710, 0.0290]), tensor([0.9788, 0.0212]), tensor([0.9374, 0.0626]), tensor([0.9835, 0.0165]), tensor([0.9744, 0.0256]), tensor([0.9788, 0.0212]), tensor([0.8720, 0.1280]), tensor([0.3271, 0.6729]), tensor([0.1273, 0.8727]), tensor([0.9615, 0.0385]), tensor([0.1273, 0.8727]), tensor([0.2646, 0.7354]), tensor([0.9638, 0.0362]), tensor([0.9662, 0.0338]), tensor([0.9806, 0.0194]), tensor([0.4777, 0.5223]), tensor([0.2292, 0.7708]), tensor([0.7444, 0.2556]), tensor([0.2023, 0.7977]), tensor([0.0646, 0.9354]), tensor([0.0636, 0.9364]), tensor([0.9615, 0.0385]), tensor([0.1739, 0.8261]), tensor([0.0736, 0.9264]), tensor([0.9747, 0.0253]), tensor([0.9683, 0.0317]), tensor([0.0551, 0.9449]), tensor([0.1040, 0.8960]), tensor([0.9611, 0.0389]), tensor([0.9571, 0.0429]), tensor([0.0839, 0.9161]), tensor([0.9571, 0.0429]), tensor([0.8192, 0.1808]), tensor([0.1224, 0.8776]), tensor([0.1877, 0.8123]), tensor([0.0654, 0.9346]), tensor([0.1789, 0.8211]), tensor([0.2487, 0.7513]), tensor([0.7

In [22]:
xlm_pred = predictions

In [28]:
indic_pred = predictions

In [44]:
m_pred = predictions

In [159]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
preds = [np.argmax(p.numpy()) for p in predictions]
# preds

In [160]:
len(test_labels)

1348

In [161]:
precision, recall, f1, _ = precision_recall_fscore_support(get_binary_labels(test_labels), preds, average='macro')
acc = accuracy_score(get_binary_labels(test_labels), preds)

In [162]:
print(f1, " ", precision," ", recall, " ", acc)

0.697035266120947   0.697035266120947   0.697035266120947   0.4844213649851632


In [47]:
a = xlm_pred
b = indic_pred
c = m_pred

## soft voting ensemble


In [48]:
preds = []

for i in range(len(m_pred)):
    a = xlm_pred[i]
    b = m_pred[i]
    c = indic_pred[i]
#     print(a, b, c)
#     print(a[0], b[0], c[0])
#     print(a[1], b[1], c[1])
    zero_score = a[0] + b[0] + c[0]
    one_score = a[1] + b[1] + c[1]
    print(zero_score, one_score)
    if(one_score >= zero_score):
        print(1)
        preds.append(1)
    else:
        preds.append(0)
        print(0)


tensor(0.3059) tensor(2.6941)
1
tensor(2.8223) tensor(0.1777)
0
tensor(0.5450) tensor(2.4550)
1
tensor(2.8548) tensor(0.1452)
0
tensor(2.8454) tensor(0.1546)
0
tensor(1.5491) tensor(1.4509)
0
tensor(2.0561) tensor(0.9439)
0
tensor(1.0763) tensor(1.9237)
1
tensor(1.4359) tensor(1.5641)
1
tensor(2.8657) tensor(0.1343)
0
tensor(2.8750) tensor(0.1250)
0
tensor(2.2753) tensor(0.7247)
0
tensor(2.8341) tensor(0.1659)
0
tensor(2.8382) tensor(0.1618)
0
tensor(1.1077) tensor(1.8923)
1
tensor(1.3386) tensor(1.6614)
1
tensor(2.5018) tensor(0.4982)
0
tensor(0.1630) tensor(2.8370)
1
tensor(1.9230) tensor(1.0770)
0
tensor(2.4874) tensor(0.5126)
0
tensor(1.7176) tensor(1.2824)
0
tensor(1.2662) tensor(1.7338)
1
tensor(1.1073) tensor(1.8927)
1
tensor(2.4421) tensor(0.5579)
0
tensor(0.7887) tensor(2.2113)
1
tensor(1.4148) tensor(1.5852)
1
tensor(2.8834) tensor(0.1166)
0
tensor(0.8571) tensor(2.1429)
1
tensor(2.6964) tensor(0.3036)
0
tensor(0.4911) tensor(2.5089)
1
tensor(0.4607) tensor(2.5393)
1
tensor(2

## hard vote

In [49]:
preds

[1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,


In [52]:
preds = []
for i in range(len(m_pred)):
    a = xlm_pred[i]
    b = m_pred[i]
    c = indic_pred[i]
#     print(a, b, c)
#     print(a[0], b[0], c[0])
#     print(a[1], b[1], c[1])
    result = [np.argmax(a.numpy()),np.argmax(b.numpy()),np.argmax(c.numpy())]
    print(result)
    zero_score = result.count(0)
    one_score = result.count(1)
    print(zero_score, one_score)
    if(one_score >= zero_score):
        print(1)
        preds.append(1)
    else:
        preds.append(0)
        print(0)

[1, 1, 1]
0 3
1
[0, 0, 0]
3 0
0
[1, 1, 1]
0 3
1
[0, 0, 0]
3 0
0
[0, 0, 0]
3 0
0
[1, 1, 0]
1 2
1
[0, 0, 1]
2 1
0
[1, 1, 1]
0 3
1
[1, 1, 0]
1 2
1
[0, 0, 0]
3 0
0
[0, 0, 0]
3 0
0
[0, 0, 0]
3 0
0
[0, 0, 0]
3 0
0
[0, 0, 0]
3 0
0
[1, 1, 0]
1 2
1
[1, 0, 1]
1 2
1
[0, 0, 0]
3 0
0
[1, 1, 1]
0 3
1
[0, 0, 1]
2 1
0
[0, 0, 0]
3 0
0
[1, 0, 1]
1 2
1
[1, 1, 0]
1 2
1
[0, 1, 1]
1 2
1
[0, 0, 0]
3 0
0
[1, 1, 1]
0 3
1
[1, 0, 1]
1 2
1
[0, 0, 0]
3 0
0
[1, 1, 0]
1 2
1
[0, 0, 0]
3 0
0
[1, 1, 1]
0 3
1
[1, 1, 1]
0 3
1
[0, 0, 0]
3 0
0
[0, 0, 1]
2 1
0
[1, 1, 1]
0 3
1
[1, 1, 1]
0 3
1
[1, 1, 1]
0 3
1
[0, 0, 0]
3 0
0
[0, 0, 0]
3 0
0
[0, 0, 0]
3 0
0
[0, 0, 0]
3 0
0
[0, 0, 1]
2 1
0
[0, 0, 1]
2 1
0
[0, 1, 0]
2 1
0
[1, 1, 1]
0 3
1
[1, 1, 1]
0 3
1
[1, 1, 1]
0 3
1
[1, 1, 1]
0 3
1
[0, 0, 0]
3 0
0
[1, 1, 1]
0 3
1
[1, 1, 1]
0 3
1
[0, 0, 0]
3 0
0
[1, 1, 1]
0 3
1
[0, 0, 0]
3 0
0
[1, 1, 1]
0 3
1
[1, 0, 1]
1 2
1
[1, 1, 1]
0 3
1
[1, 1, 0]
1 2
1
[0, 0, 1]
2 1
0
[0, 0, 0]
3 0
0
[1, 1, 1]
0 3
1
[1, 1, 1]
0 3
1
[0, 1, 0]
2 1
0
[1, 1, 1

In [19]:
indic_pred

[tensor([0.9774, 0.0226]),
 tensor([0.9844, 0.0156]),
 tensor([0.9708, 0.0292]),
 tensor([0.9680, 0.0320]),
 tensor([0.1966, 0.8034]),
 tensor([0.9753, 0.0247]),
 tensor([0.9746, 0.0254]),
 tensor([0.9700, 0.0300]),
 tensor([0.0157, 0.9843]),
 tensor([0.9731, 0.0269]),
 tensor([0.0145, 0.9855]),
 tensor([0.0180, 0.9820]),
 tensor([0.0239, 0.9761]),
 tensor([0.0169, 0.9831]),
 tensor([0.9838, 0.0162]),
 tensor([0.0193, 0.9807]),
 tensor([0.9598, 0.0402]),
 tensor([0.9692, 0.0308]),
 tensor([0.9504, 0.0496]),
 tensor([0.9547, 0.0453]),
 tensor([0.2149, 0.7851]),
 tensor([0.9731, 0.0269]),
 tensor([0.1926, 0.8074]),
 tensor([0.0170, 0.9830]),
 tensor([0.9850, 0.0150]),
 tensor([0.9861, 0.0139]),
 tensor([0.0199, 0.9801]),
 tensor([0.8577, 0.1423]),
 tensor([0.0239, 0.9761]),
 tensor([0.0196, 0.9804]),
 tensor([0.0238, 0.9762]),
 tensor([0.0196, 0.9804]),
 tensor([0.0180, 0.9820]),
 tensor([0.0178, 0.9822]),
 tensor([0.0174, 0.9826]),
 tensor([0.0179, 0.9821]),
 tensor([0.8344, 0.1656]),
 

In [4]:
import pickle
from numpy import savetxt
# a = np.array(m_pred)

# with open('pred/mbert.pickle', 'wb') as handle:
#     pickle.dump(m_pred, handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('pred/indic.pickle', 'rb') as handle:
    indic_pred = pickle.load(handle)

In [7]:
preds = [np.argmax(p.numpy()) for p in predictions]
preds

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,


In [20]:
final_preds = []
for p in preds:
    if(p==1):
        final_preds.append("HOF")
    elif(p==0):
        final_preds.append("NONE")
final_preds

['NONE',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HOF',
 'HOF',
 'NONE',
 'NON

In [21]:
submission = {'id': tweet_ids, 'label':final_preds}
submission = pd.DataFrame(submission)
submission.to_csv('submission/hard-vote-ensemble.csv', index = False)

In [22]:
submission

id label
0     1396844054818680835  NONE
1     1396844158283776004  NONE
2     1397043581446098945  NONE
3     1398265913749635073  NONE
4     1396852220268716032   HOF
...                   ...   ...
1343  1397189986437537803  NONE
1344  1397209328013164548  NONE
1345  1397217889237745666  NONE
1346  1397224681229504520   HOF
1347  1397400844258013190   HOF

[1348 rows x 2 columns]

In [23]:
a = pd.read_csv('submission/hard-vote-ensemble.csv')
b = pd.read_csv('submission/soft-vote-ensemble.csv')

In [26]:
b = b["label"].tolist()
a=a["label"].tolist()

In [27]:
count = 0
for i in range(len(a)):
    if(a[i]!=b[i]):
        count+=1

In [28]:
count

40